Repository cowprotocol/explorer, pull requests merged in 2022-08, with the labels that each got.

#171 Show up to 2 decimals
  src/components/orders/FilledProgress/index.tsx
Labels: app:Explorer, Protofire

#181 Release/2.11.0
  package.json
  src/assets/img/CowProtocol-icon.svg
  src/assets/img/CowProtocol-logo-white.svg
  src/components/layout/GenericLayout/Header/index.tsx
  src/components/orders/FilledProgress/index.tsx
  yarn.lock
Labels: RELEASE

#168 [Explorer] Add Metadata page
  package.json
  src/apps/explorer/ExplorerApp.tsx
  src/apps/explorer/pages/AppData/DecodePage.tsx
  src/apps/explorer/pages/AppData/FormPage.tsx
  src/apps/explorer/pages/AppData/config.tsx
  src/apps/explorer/pages/AppData/index.tsx
  src/apps/explorer/pages/AppData/styled.ts
  src/components/AppData/DecodeAppData.tsx
  src/components/Notification.tsx
  src/components/common/AppDataWrapper/index.tsx
  src/components/icons/index.tsx
  src/components/orders/DetailsTable/index.tsx
  yarn.lock
Labels: Enhancement

#172 Adding tag partial fill when order is partially filled
  package.json
  src/components/Icon.tsx
  src/components/orders/DetailsTable/index.tsx
  src/components/orders/OrderPriceDisplay/index.tsx
  src/components/orders/OrdersUserDetailsTable/index.tsx
  src/components/orders/StatusLabel/StatusLabel.stories.tsx
  src/components/orders/StatusLabel/index.tsx
  src/components/transaction/TransactionTable/index.tsx
  src/components/transaction/TransactionTable/styled.ts
  yarn.lock
Labels: app:Explorer, Protofire

#194 Hardcode zero address for ipfs fetching
  src/const.ts
Labels: Bug

#189 Release v2.12.0
  .nvmrc
  package.json
  src/api/operator/constants.ts
  src/api/operator/operatorApi.ts
  src/api/operator/signatures.ts
  src/api/tenderly/tenderlyApi.ts
  src/api/web3/index.ts
  src/apps/explorer/ExplorerApp.tsx
  src/apps/explorer/components/SummaryCardsWidget/SummaryCards.tsx
  src/apps/explorer/components/SummaryCardsWidget/VolumeChart/VolumeChart.tsx
  src/apps/explorer/components/SummaryCardsWidget/VolumeChart/useGetVolumeData.ts
  src/apps/explorer/components/SummaryCardsWidget/useGetSummaryData.ts
  src/apps/explorer/components/TransanctionBatchGraph/index.tsx
  src/apps/explorer/const.ts
  src/apps/explorer/pages/AppData/DecodePage.tsx
  src/apps/explorer/pages/AppData/EncodePage.tsx
  src/apps/explorer/pages/AppData/config.tsx
  src/apps/explorer/pages/AppData/index.tsx
  src/apps/explorer/pages/AppData/styled.ts
  src/components/AppData/DecodeAppData.tsx
  src/components/Icon.tsx
  src/components/NetworkSelector/NetworkSelector.styled.ts
  src/components/NetworkSelector/index.tsx
  src/components/Notification.tsx
  src/components/common/AppDataWrapper/index.tsx
  src/components/common/Card/card.utils.ts
  src/components/icons/index.tsx
  src/components/orders/DetailsTable/index.tsx
  src/components/orders/FilledProgress/FilledProgress.stories.tsx
  src/components/orders/FilledProgress/index.tsx
  src/components/orders/OrderDetails/index.tsx
  src/components/orders/OrderNotFound/index.tsx
  src/components/orders/OrderPriceDisplay/index.tsx
  src/components/orders/OrderSurplusDisplay/OrderSurplusDisplay.stories.tsx
  src/components/orders/OrdersUserDetailsTable/index.tsx
  src/components/orders/StatusLabel/StatusLabel.stories.tsx
  src/components/orders/StatusLabel/index.tsx
  src/components/transaction/TransactionTable/index.stories.tsx
  src/components/transaction/TransactionTable/index.tsx
  src/components/transaction/TransactionTable/styled.ts
  src/const.ts
  src/hooks/useAppData.ts
  src/hooks/useGetTokens.ts
  src/hooks/useOperatorTrades.ts
  src/state/network/updater.tsx
  src/styles/colours.ts
  src/utils/contract.ts
  src/utils/miscellaneous.ts
  test/data/operator.ts
  test/utils/operator/orderFilledAmount.test.ts
  test/utils/operator/orderPrice.test.ts
  test/utils/operator/orderStatus.test.ts
  test/utils/operator/orderSurplus.test.ts
  webpack.config.js
  yarn.lock
Labels: Protofire, app:CowSwap, RELEASE

#197 [Top Tokens Table] Rename some columns
  src/components/token/TokenTable/index.tsx
Labels: Enhancement

#202 [AppData] Store data when switching beetween tabs
  src/apps/explorer/pages/AppData/DecodePage.tsx
  src/apps/explorer/pages/AppData/EncodePage.tsx
  src/apps/explorer/pages/AppData/index.tsx
  src/apps/explorer/pages/AppData/styled.ts
Labels: Enhancement

#203 [App Data] Remove default version values + read only fields
  package.json
  src/apps/explorer/pages/AppData/config.tsx
  yarn.lock
Labels: Enhancement, Protofire
