Repository cowprotocol/explorer, pull requests merged in 2022-06, with the labels that each got.

#105 Fetch orders and order detail from barn and prod apis
  src/api/operator/operatorApi.ts
  src/const.ts
  src/hooks/useGetOrders.tsx
  src/hooks/useOperatorOrder.ts
  src/services/helpers/tryGetOrderOnAllNetworks.ts
  test/services/tryGetOrderOnAllNetworks.test.ts
Labels: Protofire

#100 [Batch Viewer] Add a Reset button + autoscale graph area
  src/apps/explorer/components/TransanctionBatchGraph/index.tsx
  src/apps/explorer/components/TransanctionBatchGraph/styled.ts
  src/apps/explorer/components/common/ExplorerTabs/ExplorerTabs.tsx
  src/types/cytoscape.d.ts
Labels: app:Explorer, Enhancement, Medium, Protofire

#103 [Batch Viewer] Zoom and drag improvements
  package.json
  src/apps/explorer/components/TransanctionBatchGraph/index.tsx
  src/apps/explorer/components/TransanctionBatchGraph/styled.ts
  src/declarations.d.ts
  src/types/cytoscape.d.ts
  yarn.lock
Labels: app:Explorer, Bug, Medium, Protofire

#107 Update summary cards each 30 seconds
  src/apps/explorer/components/SummaryCardsWidget/useGetSummaryData.ts
Labels: app:Explorer, Protofire

#108 [Batch Viewer] Differentiate SELL and BUY orders
  src/api/operator/operatorApi.ts
  src/apps/explorer/components/TransactionsTableWidget/index.tsx
  src/apps/explorer/components/TransanctionBatchGraph/elementsBuilder.tsx
  src/apps/explorer/components/TransanctionBatchGraph/index.tsx
  src/apps/explorer/components/TransanctionBatchGraph/styled.ts
  src/apps/explorer/components/TransanctionBatchGraph/types.ts
  src/const.ts
  src/hooks/useGetOrders.tsx
  src/hooks/useOperatorOrder.ts
  src/hooks/useTxBatchTrades.tsx
  src/services/helpers/tryGetOrderOnAllNetworks.ts
  test/services/tryGetOrderOnAllNetworks.test.ts
Labels: Enhancement, Protofire

#98 Integrate Tokens table data from the subgraph
  .github/workflows/ci.yml
  package.json
  src/api/operator/types.ts
  src/apps/explorer/components/SummaryCardsWidget/VolumeChart/useGetVolumeData.ts
  src/apps/explorer/components/SummaryCardsWidget/VolumeChart/volumeData.json
  src/apps/explorer/components/SummaryCardsWidget/useGetSummaryData.ts
  src/apps/explorer/components/SummaryCardsWidget/utils.ts
  src/apps/explorer/components/TokensTableWidget/TokensTableWithData.tsx
  src/apps/explorer/components/TokensTableWidget/context/TokensTableContext.tsx
  src/apps/explorer/components/TokensTableWidget/index.tsx
  src/apps/explorer/components/TokensTableWidget/useTable.tsx
  src/apps/explorer/components/common/TablePagination/index.tsx
  src/components/token/TokenTable/index.tsx
  src/data/tokens.ts
  src/hooks/useFlexSearch.ts
  src/hooks/useGetTokens.ts
  yarn.lock
Labels: Protofire

#113 Increase column, show dash and use tooltip mobile
  src/components/orders/OrderSurplusDisplay/index.tsx
  src/components/orders/OrdersUserDetailsTable/OrderSurplusTooltipStyledByRow.tsx
  src/components/orders/OrdersUserDetailsTable/index.tsx
Labels: app:Explorer, Protofire

#116 Make batch viewer tooltip persistent on mobile
  src/apps/explorer/components/TransanctionBatchGraph/index.tsx
Labels: Protofire

#58 Home page Epic
  .github/workflows/ci.yml
  package.json
  src/apps/explorer/components/OrdersTableWidget/OrdersTableWithData.tsx
  src/apps/explorer/components/OrdersTableWidget/context/OrdersTableContext.tsx
  src/apps/explorer/components/OrdersTableWidget/index.tsx
  src/apps/explorer/components/SummaryCardsWidget/SummaryCards.tsx
  src/apps/explorer/components/SummaryCardsWidget/VolumeChart/VolumeChart.stories.tsx
  src/apps/explorer/components/SummaryCardsWidget/VolumeChart/VolumeChart.styled.ts
  src/apps/explorer/components/SummaryCardsWidget/VolumeChart/VolumeChart.tsx
  src/apps/explorer/components/SummaryCardsWidget/VolumeChart/VolumeChartWidget.tsx
  src/apps/explorer/components/SummaryCardsWidget/VolumeChart/useGetVolumeData.ts
  src/apps/explorer/components/SummaryCardsWidget/VolumeChart/volumeData.json
  src/apps/explorer/components/SummaryCardsWidget/index.tsx
  src/apps/explorer/components/SummaryCardsWidget/summaryData.json
  src/apps/explorer/components/SummaryCardsWidget/useGetSummaryData.ts
  src/apps/explorer/components/SummaryCardsWidget/utils.ts
  src/apps/explorer/components/TokensTableWidget/TokensTableWithData.tsx
  src/apps/explorer/components/TokensTableWidget/context/TokensTableContext.tsx
  src/apps/explorer/components/TokensTableWidget/index.tsx
  src/apps/explorer/components/TokensTableWidget/useTable.tsx
  src/apps/explorer/components/common/ExplorerTabs/ExplorerTabs.tsx
  src/apps/explorer/components/common/ShimmerBar/index.tsx
  src/apps/explorer/components/common/TablePagination/index.tsx
  src/apps/explorer/pages/Home/index.tsx
  src/apps/explorer/pages/styled.tsx
  src/apps/explorer/styled.ts
  src/assets/img/graph-skeleton.svg
  src/components/common/Card/Card.tsx
  src/components/common/Card/CardContent.tsx
  src/components/common/Card/card.utils.ts
  src/components/common/Card/index.tsx
  src/components/common/CardRow/CardRow.stories.tsx
  src/components/common/CardRow/index.tsx
  src/components/common/CopyButton/index.tsx
  src/components/common/RowWithCopyButton/index.tsx
  src/components/common/StyledUserDetailsTable.tsx
  src/components/common/TableSearch/TableSearch.tsx
  src/components/common/Tabs/Tabs.tsx
  src/components/orders/OrdersUserDetailsTable/index.tsx
  src/components/token/TokenTable/index.tsx
  src/hooks/useFlexSearch.ts
  src/hooks/useGetTokens.ts
  src/theme/styles/colours.ts
  src/theme/styles/global.ts
  yarn.lock
Labels: app:Explorer, Protofire

#125 Update gnosis chain rpc endpoint
  src/api/web3/index.ts
  src/utils/walletconnectOptions.ts
Labels: app:Explorer, Protofire

#126 Bump Version to 2.8.2
  package.json
Labels: app:Explorer, Protofire

#127 Update develop branch with hotfix/v2.8.2
  package.json
  src/api/web3/index.ts
  src/utils/walletconnectOptions.ts
Labels: app:Explorer, Protofire

#128 [Batch Viewer] Avoid multiple requests to Tenderly API
  src/apps/explorer/components/SummaryCardsWidget/VolumeChart/VolumeChart.tsx
  src/hooks/usePrevious.ts
  src/hooks/useTxBatchTrades.tsx
Labels: Bug, Protofire

#146 Remove popper when reset, change layout or component unmount
  src/apps/explorer/components/TransanctionBatchGraph/index.tsx
  src/apps/explorer/components/common/Dropdown/index.tsx
Labels: app:Explorer, Protofire

#153 Update develop branch with Release/v2.9.0
  package.json
  src/api/operator/operatorApi.ts
  src/apps/explorer/components/TransanctionBatchGraph/index.tsx
  src/apps/explorer/components/common/Dropdown/index.tsx
  src/components/orders/OrderNotFound/index.tsx
  src/hooks/useErc20.ts
  src/hooks/useOperatorTrades.ts
  src/hooks/useTxBatchTrades.tsx
  src/services/helpers/tryGetOrderOnAllNetworks.ts
  yarn.lock
Labels: app:Explorer, Protofire
