Repository cowprotocol/explorer, pull requests merged in 2023-06, with the labels that each got.

#508 feat(batch-graph): special addresses
  src/api/tenderly/tenderlyApi.ts
  src/apps/explorer/components/TransanctionBatchGraph/styled.ts
  src/apps/explorer/components/TransanctionBatchGraph/types.ts
  src/apps/explorer/components/TransanctionBatchGraph/utils.ts
  src/apps/explorer/const.ts
  src/hooks/useTxBatchTrades.tsx
Labels: RELEASE

#515 fix: fix surplus calculation for very big numbers
  src/utils/operator.ts
Labels: RELEASE

#523 Release/2.23.0
  package.json
  src/api/tenderly/tenderlyApi.ts
  src/api/tenderly/types.ts
  src/apps/explorer/components/TransanctionBatchGraph/elementsBuilder.tsx
  src/apps/explorer/components/TransanctionBatchGraph/hooks.ts
  src/apps/explorer/components/TransanctionBatchGraph/index.tsx
  src/apps/explorer/components/TransanctionBatchGraph/styled.ts
  src/apps/explorer/components/TransanctionBatchGraph/types.ts
  src/apps/explorer/components/TransanctionBatchGraph/utils.ts
  src/apps/explorer/const.ts
  src/apps/explorer/styled.ts
  src/components/common/BlockExplorerLink/BlockExplorerLink.tsx
  src/components/orders/GasFeeDisplay/index.tsx
  src/hooks/useTxBatchTrades.tsx
  src/utils/getExplorerUrl.ts
  src/utils/operator.ts
  yarn.lock
Labels: RELEASE

#530 Hackaton/tenderly data loading
  src/api/tenderly/tenderlyApi.ts
  src/hooks/useTransactionData.ts
Labels: app:CowSwap, hackaton

#531 Hackaton/nodes and edges
  src/api/tenderly/index.ts
  src/api/tenderly/tenderlyApi.ts
  src/apps/explorer/components/TransanctionBatchGraph/alternativeView/index.ts
Labels: hackaton

#534 Hackathon graph
  src/api/tenderly/index.ts
  src/api/tenderly/tenderlyApi.ts
  src/api/tenderly/types.ts
  src/apps/explorer/components/TransactionsTableWidget/index.tsx
  src/apps/explorer/components/TransanctionBatchGraph/elementsBuilder.tsx
  src/apps/explorer/components/TransanctionBatchGraph/hooks.ts
  src/apps/explorer/components/TransanctionBatchGraph/index.tsx
  src/apps/explorer/components/TransanctionBatchGraph/layouts.ts
  src/apps/explorer/components/TransanctionBatchGraph/nodesBuilder.ts
  src/apps/explorer/components/TransanctionBatchGraph/settlementBuilder.tsx
  src/apps/explorer/components/TransanctionBatchGraph/styled.ts
  src/apps/explorer/components/TransanctionBatchGraph/types.ts
  src/apps/explorer/components/TransanctionBatchGraph/utils.ts
  src/apps/explorer/styled.ts
  src/const.ts
  src/hooks/useTransactionData.ts
  src/hooks/useTxBatchTrades.tsx
Labels: hackathon

#542 Release/2.24.0
  package.json
  src/api/tenderly/index.ts
  src/api/tenderly/tenderlyApi.ts
  src/api/tenderly/types.ts
  src/apps/explorer/components/TransactionsTableWidget/index.tsx
  src/apps/explorer/components/TransanctionBatchGraph/elementsBuilder.tsx
  src/apps/explorer/components/TransanctionBatchGraph/hooks.ts
  src/apps/explorer/components/TransanctionBatchGraph/index.tsx
  src/apps/explorer/components/TransanctionBatchGraph/layouts.ts
  src/apps/explorer/components/TransanctionBatchGraph/nodesBuilder.ts
  src/apps/explorer/components/TransanctionBatchGraph/settlementBuilder.tsx
  src/apps/explorer/components/TransanctionBatchGraph/styled.ts
  src/apps/explorer/components/TransanctionBatchGraph/types.ts
  src/apps/explorer/components/TransanctionBatchGraph/utils.ts
  src/apps/explorer/styled.ts
  src/const.ts
  src/hooks/useTransactionData.ts
  src/hooks/useTxBatchTrades.tsx
Labels: RELEASE
